### ISSUE TITLE
CLRS Presentation

### ISSUE THREAD

**Issue by rajesh06** [mages/ChainLadder#24]
I am one of the presenters at the R workshop at CLRS (2016). I was assigned the `ChainLadder` package. Here is my presentation in case you have any thoughts (no obligation, of course)
http://rpubs.com/rajesh06_2016/chainladder_clrs

Thanks - Raj

**Comment by mages** [comment]
Thanks for sharing!

**Comment by chiefmurph** [comment]
I signed in to RPubs and went to http://rpubs.com/rajesh06_2016/chainladder_clrs but can only see the title page.

**Comment by rajesh06** [comment]
It works fine for me. You may need to click on the title slide to "activate" it.
FYI - I made some minor changes over the weekend.

**Comment by mages** [comment]
It worked for me as well with Google Chrome.

**Comment by chiefmurph** [comment]
Nope, still doesn't work. May be a permissions issue. I will try publishing
something to RPubs myself so see if that helps.

**Comment by chiefmurph** [comment]
User error! Scroll wheel and clicking do not work with a slide
presentation. Stumbled on Page Down.

**Comment by rajesh06** [comment]
Great - if you want the Rmd file, its here:
https://github.com/PirateGrunt/raw_clrs/tree/master/Rmd

**Comment by chiefmurph** [comment]
Forked the repository and will look at your slides. 
BTW, knit error due to uninstalled 'raw' package. FWIW, the Basic Data slides make no mention of how to install, which I did via
> library(devtools)
> install_github("PirateGrunt/raw")

**Comment by chiefmurph** [comment]
User error again. The version of raw on PirateGrunt does not contain NJM_WC, but the version on CRAN does. Ignore my previous install_github.

**Comment by chiefmurph** [comment]
Raj,

Thank you for sharing your Rmd and R files. 

I like how you formatted the 40_ChainLadder section into material and exercises. I've always found Exercises to be the best instruction. 

I have two major suggestions:

1. You go through a lot to generate the development factor plot on slide 16, and kudos for that! (I wasn't sure if part of your motivation was to teach the "tibble" package or not.) Although 'plot' alone will generate a plot of a matrix of age-to-age factors, I think your demonstration of ggplot will be well-received. ... However, ChainLadder shouldn't make it so hard for you to generate the data.frame that drives that plot! The 'ata' function in ChainLadder can calculate the link ratios, with a little extra "sugar", like the ability to label the columns as "1 to 2", etc. And I wrote a new, exported ChainLadder function 'as.LongTriangle' which will convert from matrix to data.frame and allow you to rename the columns, among other things. Once Markus accepts the pull request, then as.LongTriangle will be ready to go to CRAN (hopefully by 9/30). In the meantime, you can try the new functionality from my fork by
library(devtools)
install_github("chiefmurph/ChainLadder")

2. The uncertainty estimates from the CLFM paper are already available in ChainLadder. The only thing missing is the psi function from that paper. However, even without that extra twist, the additional standard error using CLFM vs. plain Mack can be significant. I added a couple of lines to the R script to demonstrate how to get those estimates.

Finally, I'm not sure what is meant on slide 25 by "tail ~ c("G", "maxage")" but maybe that's still TBD.

Nice work! Hope these comments help. Let me know if questions. We can take this offline via email if that's more convenient.
Dan

**Comment by rajesh06** [comment]
Thanks Dan - That is very helpful and I appreciate the time you took to review and write this up. I will respond offline - as this is probably beyond an "issue" discussion at this point. (If it ever was)

Thanks again - Raj
