### ISSUE TITLE
Error: package or namespace load failed for ‘ChainLadder’

### ISSUE THREAD

**Issue by nmeraihi** [mages/ChainLadder#28]
I tried to install a package on a [jupyter notebook](http://jupyter.org)  i`nstall.packages("ChainLadder", "/Users/mymac/anaconda/lib/R/library")` and I have this message when I load `library(ChainLadder)`
any idea?
thanks!

> Error: package or namespace load failed for ‘ChainLadder’
> 
> Traceback:
> 
> library(ChainLadder)
> 
> stop(gettextf("package or namespace load failed for %s", sQuote(package)),
> 
> . call. = FALSE, domain = NA)

**Comment by chiefmurph** [comment]
Jupyter looks interesting, but I have not tried it. (Mages?) 

One thought: when you install a package under Jupyter, do you automatically install all dependencies? 

Curious, Nmeraihi, if you can share any applications you have successfully run under jupyter that use non-base R packages. If not or too difficult, no worries. Thanks.
-Dan

**Comment by nmeraihi** [comment]
I also installed all the dependencies `install.packages(c("systemfit", "actuar", "statmod", "tweedie"))` and they work very well. 
I use Jupyter notebook for every thing I do with Python, R and Matlab. Because I have every thing I need + Markdown

**Comment by chiefmurph** [comment]
There are many more needed, but perhaps you have already installed them. Thanks for the feedback. Can this issue be closed?

**Comment by nmeraihi** [comment]
But `ChainLadder` package is still not working. Maybe someone has the answer?

**Comment by mages** [comment]
I don't think that this is a ChainLadder issue as such. I suggest you ask this question on the Jupyter forum: https://groups.google.com/forum/#!forum/jupyter

**Comment by nmeraihi** [comment]
Thank you @mages ,
