### ISSUE TITLE
Adjusted Pearson residual calculation in BootChainLadder

### ISSUE THREAD

**Issue by ColmQ** [mages/ChainLadder#32]
Within the BootChainLadder function, adjusted Pearson residuals are calculated as follows:

_adj.resids <- unscaled.residuals * sqrt(nobs/scale.factor)_

This is consistent with the formula given in the "Addendum to 'Analytic and Bootstrap Estimates of Prediction Errors in Claims Reserving'" paper (England, 2001, equations 2.4 and 3.1).

However, it is _not_ consistent with the Stochastic Claims Reserving In General Insurance paper (England & Verrall, 2002, Appendix 3). Here the bootstrapping procedure is described with the instruction to adjust the Pearson residuals using the following slightly different formula:

_adj.resids <- unscaled.residuals * sqrt(n/scale.factor)_

i.e. with _n_ rather than _nobs_ in the numerator. 

_n_ is the number of rows/columns in the claims triangle, _nobs_ is the total number of data points observed ( _nobs <- 0.5 * n * (n + 1)_ ),  and _scale.factor <- (nobs - 2 * n + 1)_, or "_n - p_" in the original paper.

The latter source is the paper actually referenced in the R help file for BootChainLadder, although this in turn references the former.

Does anybody know how the Pearson residual adjustment formula is derived? Are there cases for using either version or is one incorrect? There can be a significant impact on the resulting calculation of standard error of IBNR depending on which is used.

**Comment by chiefmurph** [comment]
I think it is just a typo in Appendix 3 of the 2002 paper where the 'n' in the numerator under the square root is supposed to be 'N' = nobs. See for example "step 7" on p. 6 of https://www.casact.org/pubs/forum/12sumforum/Leong_Wang_Chen.pdf. 

Appendix 3's type-setting is not the best after all, just look at the indices of the summation sign in the numerator of the calculation for phi. 

So where you say "scale.factor <- (nobs - 2 * n + 1), or 'n - p' in the original paper", the intent of 'n' in the original (2001) paper is N = nobs.
