### ISSUE TITLE
Mack method standard errors NaN issue

### ISSUE THREAD

**Issue by PatrickGreen123** [mages/ChainLadder#39]
The Mack method returns NaN for the the standard error if  "sigma[i - 2]^2" is zero in the Mack.S.E function.

**Comment by PatrickGreen123** [comment]
I think I have fixed this now

**Comment by mages** [comment]
Hi there, this looks good. Could you please provide the test data set/ triangle that caused the issue. I't like to add a test to the build process, ensuring the issue doesn't arise again. Thanks

**Comment by PatrickGreen123** [comment]
Hi Markus,


I can't give you the triangle that revealed the bug, but you can find attached a made up triangle which should reproduce the NAN issue.


The triangle is completely unrealistic but hopefully that doesn't matter to you.


Kind Regards,

Patrick

________________________________

**Comment by mages** [comment]
Hi Patrick, 
a made up triangle is exactly, what I am looking for. Unfortunately, it didn't seem to attached. Best, it you load into R and paste the output of 
```s
dput(triangle)
```
Thanks
Markus

**Comment by PatrickGreen123** [comment]
Try this link:

https://drive.google.com/file/d/0B605tTCPt_5sT2JvRGswUW1STVE/view?usp=drivesdk

If that doesn't work then I'll try your suggestion

---- Markus Gesmann wrote ----


Hi Patrick,
a made up triangle is exactly, what I am looking for. Unfortunately, it didn't seem to attached. Best, it you load into R and paste the output of

dput(triangle)

Thanks
Markus

**Comment by mages** [comment]
Got it. Thanks.

**Comment by mages** [comment]
Updated package, version 0.2.5, on its way to CRAN. Thanks again.
