### ISSUE TITLE
CDR at 99.5%

### ISSUE THREAD

**Issue by Free-rider** [mages/ChainLadder#4]
I am trying to calculate the CDR for solvency II proposes. How can I get the CDR from BootChainLadder object at 99.5% ? Thanks!

updated: CDR(BCL, probs=c(0.995))

**Comment by chiefmurph** [comment]
Please read Markus' blog and example here:
http://www.magesblog.com/2015/03/chainladder-020-adds-solvency-ii-cdr.html?m=1
Hope that helps.
Dan

**Comment by mages** [comment]
It's quite simple. There is an argument for that:

> library(ChainLadder)
> set.seed(1)
> B <- BootChainLadder(RAA)
> CDR(B, probs=0.995)
            IBNR   IBNR.S.E  CDR(1)S.E CDR(1)99.5%
1981      0.0000     0.0000     0.0000       0.000
1982    201.8727   738.9566   738.9566    3586.522
1983    701.7293  1312.3666  1093.9933    4732.426
1984   1714.5232  1975.1876  1435.5236    7598.519
1985   2717.7202  2166.9789  1562.4295    8722.895
1986   3728.3322  2445.9520  1829.9943   10438.143
1987   5413.8329  3127.7957  2136.4822   12854.808
1988  10879.2099  5003.5989  3451.7499   22376.221
1989  10936.4075  6086.9802  4703.2961   26506.884
1990  16831.3456 13323.5153 11328.3650   57238.396
Total 53124.9736 18679.4567 15302.9446  101143.77
