### ISSUE TITLE
A misspelling in the vignette?

### ISSUE THREAD

**Issue by timmyshen** [mages/ChainLadder#41]
https://github.com/mages/ChainLadder/blob/3ef97310bc4cb63675d66e3b6c672d0e518edb14/vignettes/ChainLadder.Rnw#L286

Hi,

Wonder if the example should be that "the age of the **13112** value, evaluated as of 1990, is three years". Looks like a typo to me.

Regards,
Ben

**Comment by trinostics** [comment]
You are correct, Ben. That's the correct value in the column labeled '3' of
the RAA triangle for origin year 1988.
