### ISSUE TITLE
Origin is missing when no claims into the origin year

### ISSUE THREAD

**Issue by bparvanov1** [mages/ChainLadder#43]
Hi all, Greate library.
Playing with demo ""DatabaseExamples"" i have added data for new lob (Marine1) in MSAccess data base. As you can see some data are missing (origin year 2013 missing claims)

Marine1 | 0 | 1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | -- | -- | --
2012 | 17850 |   |   |   |   |  
2013 |   |   |   |   |   |  
2014 | 1167.96 | 53010 |   |   |   |  
2015 |   |   | 4900 |   |   |  
2016 | 9308.33 | 69289.5 |   |   |   |  
2017 | 377 |   |   |   |   |  

as a result Origin years are missing and replaced by  .... (1,3,4,5,6) instead of 2012, **_2013 is not reported at all_** , 2014, 2015, 2016, 2017

> BootChainLadderResults
$Marine1
FUN(Triangle = X[[i]], R = 999, process.distr = ..2)

  | Latest | Mean Ultimate | Mean IBNR | IBNR.S.E | IBNR 75% | IBNR 95%
-- | -- | -- | -- | -- | -- | --
1 | 17,850 | 17,850 | 0 | 0 | 0 | 0
3 | 54,178 | 54,178 | 0 | 0 | 0 | 0
4 | 4,900 | 4,900 | 0 | 0 | 0 | 0
5 | 78,598 | 78,598 | 0 | 0 | 0 | 0
6 | 377 | 377 | 0 | 0 | 0 | 0

                 Totals
Latest:         155,903
Mean Ultimate:  155,903
Mean IBNR:            0
IBNR.S.E              0
Total IBNR 75%:       0
Total IBNR 95%:       0

**Comment by mages** [comment]
It looks like you tried to add your own data in a triangle shape to the MS Access example database. However, you will have to store your triangle in a long format, i.e. reshape the triangle with as.data.frame.triangle first. Unfortunately, I haven't got access to MS Access anymore. You can find the script that I used to create the database here: https://github.com/mages/ChainLadder/blob/master/inst/Database/CreateTestData.R
