### ISSUE TITLE
Interest for a method to extract the diagonal?

### ISSUE THREAD

**Issue by vigou3** [mages/ChainLadder#45]
I'd find useful when working with the package to be able to easily extract the SO-NE diagonal of a triangle, the same way `base:::diag` extracts the NO-SE diagonal of a matrix.

Would this be a welcome addition to the package? I'll gladly contribute the patch.

**Comment by trinostics** [comment]
:-) Took me a second to realize your compass headings are in French!
getLatestCumulative does not work for you?

**Comment by vigou3** [comment]
Argh! The French for *West* is pronounced the same as in English, only the spelling is different. Sorry about that.

Ah, indeed, `getLatestCumulative` does exactly what I meant. I didn't know about the function.
