### ISSUE TITLE
Creation of triangle objects

### ISSUE THREAD

**Issue by vigou3** [mages/ChainLadder#46]
Another enhancement proposal I'm willing to work on.

Currently, one creates triangle objects using `as.triangle` on matrices or data frames. This works very well for imported data, but I think we could do better for triangles created from the command line (or in a script file, which amounts to the same).

Just like there are `matrix` and `as.matrix`, or `data.frame` and `as.data.frame`, we could have a function `triangle` to directly create triangle objects from vectors of data. The added benefit would be that one would *not* have to supply `NA` values for the lower triangle. Think of an interface similar to this to create a 4 x 4 triangle:

```
triangle(c(1:4), c(1:3), c(1:2), 1, byrow = TRUE)
```

Any interest?

Cheers

**Comment by mages** [comment]
My understanding of Vincent's proposal is that ```triangle(c(1:4), c(1:3), c(1:2), 1, byrow = TRUE)``` would produces a triangle that looks like this:
```s
1 2 3 4
1 2 3 NA
1 2 NA NA
1 NA NA NA
```

**Comment by vigou3** [comment]
The understanding of Markus is correct. Sorry if I wasn't clear enough, I put together a toy example pretty quickly.

Dan: your `bydiag`  idea is great! The only drawback UI wise would be that this would mean three arguments (`byrow`, `bycol`, `bydiag`) instead of a toggle (TRUE/FALSE). 

Do you think it's worth working on this?
