### ISSUE TITLE
Plot of ClarkLDF not showing p value

### ISSUE THREAD

**Issue by loverway** [mages/ChainLadder#49]
When plotting ClarkLDF the Normal Q-Q Plot is showing "Shapiro-Wilk p. value = 0."

Is there a way to show the rest of the p value?
![image](https://user-images.githubusercontent.com/39125522/40740616-45525d00-6417-11e8-95a9-cb7e7883cae7.png)

**Comment by trinostics** [comment]
Dear loverway:

These are the three lines that calculate the p value to display (see clark.r, lines 862-864):

  N <- min(length(x$stdresid),5000) # 5000=shapiro.test max sample size  
  shap.p <- shapiro.test(sample(x$stdresid,N))  
  shap.p.value <- round(shap.p$p.value,5)

where x is the "clark object" (the result of ClarkLDF or ClarkCapeCod).

E.g.,
> x <- ClarkLDF(GenIns)
> plot(x)
![capture](https://user-images.githubusercontent.com/6462471/40745923-b4b71140-640d-11e8-81c4-04227d0d88cc.JPG)

> N <- min(length(x$stdresid),5000)
> shap.p <- shapiro.test(sample(x$stdresid,N))
> shap.p

	Shapiro-Wilk normality test

data:  sample(x$stdresid, N)
W = 0.95272, p-value = 0.03037

Is this what you were looking for?

-Dan

**Comment by loverway** [comment]
That did help. My p value was really small and it looks like it only shows "0." if the p value is too small. It displays a few decimals of the p value for the RAA data. Thanks for your help.
