### ISSUE TITLE
Modify documentation to make the weights parameter of chainladder more clear

### ISSUE THREAD

**Issue by ben519** [mages/ChainLadder#5]
In the chainladder() method, it was unclear to me how the weights matrix would be applied.  I mistakenly assumed that the weight W_{i,j+1} corresponded to the age-to-age factor given by C_{i,j+1}/C_{i,j}.  Turns out the weight W_{i,j} corresponds to that factor.

Didn't see any mention of this in the documentation.  Would be nice to include it so others don't make the same mistake I did.

Thanks

**Comment by mages** [comment]
Please make a pull request on the file it self with your suggestion. I thought the details section clarifies how the weights will be applied. 
Thanks

**Comment by ben519** [comment]
I read through the details section.  To me it still seems ambiguous how the weights in W could be applied.  I'll work on that pull request this weekend.

**Comment by mages** [comment]
Thanks for your pull request.
