### ISSUE TITLE
as.triangle for data.frame has bug with column names

### ISSUE THREAD

**Issue by edwardtasker** [mages/ChainLadder#60]
Line 85 in "Triangles.R" has a bug which leads to incorrect naming of columns:

In the following code, the order of "dev" and "origin" are swapped in the aggregate function and the line which names the columns.

 aggTriangle <- stats::aggregate(Triangle[[value]], 
                        list(Triangle[[dev]], Triangle[[origin]]), 
                        sum)
  names(aggTriangle) <- c(origin, dev, value)

**Comment by mages** [comment]
Thanks for reporting! Should be fixed now in the version on GitHub
