### ISSUE TITLE
Process and parameter error

### ISSUE THREAD

**Issue by Rick132** [mages/ChainLadder#7]
Hello!
Please I have 2 questions and really hope someone will help me to understand.

1.Is there any way to find the process and parameter error from the Mack ChainLadder output? Is  process and parameter error the same as the process risk and parameter risk that the package provide? If they are, Is the sum of the two not supposed to be equal to Mack.S.E for a given accident year? 

2. My second question is about glmReserve in the ChainLadder package. If I set var.power= NULL, it returns "var.power must be provided for this version" although the vignette expressed that the package can return a var.power that fits the data when you set var.power=NULL.

Am I missing something? I need help on these issues.

Thanks in advance

**Comment by trinostics** [comment]
I will respond to #1:

Is process and parameter error the same as the process risk and parameter risk that the package provide?

Yes

 Is the sum of the two not supposed to be equal to MackSE for a given accident year?

No. You do not add the errors, but use the Pythagorean theorem equivalent formula:
MackSE = sqrt(processrisk^2 + parameterrisk^2)

**Comment by Rick132** [comment]
Thank you very much! That really helped!

**Comment by actuaryzhang** [comment]
Regarding your second question, you need the newest version of ChainLadder 0.2.2 to estimate the power of the variance function. What version were you using?

**Comment by Rick132** [comment]
Hey!
I am using version 0.2.0. It seems version 0.2.2 doesnot exist on R for
macbook.

**Comment by actuaryzhang** [comment]
There are binaries for Mac on CRAN for version 0.2.2. 
Or you can download the source file and run install.packages on that. 
Let me know if it still does not work.

**Comment by Rick132** [comment]
Hello!
Thanks for the response. I have just installed Chain Ladder on Windows PC
and got the version 0.2.2. "var.power=NULL" works on that.
However reinstalling Chain Ladder on Mac (at least on mine) returns version
0.2.0 and get an error for var.power=NULL.
 See below :
> install.packages("ChainLadder")

  There is a binary version available (and will be installed) but the
source version is later:
            binary source
ChainLadder  0.2.0  0.2.2

Error: Error in glmReserve(as.triangle(inc.triangle), var.power = NULL,
link.power = 0,  :
  var.power must be provided for this version

**Comment by trinostics** [comment]
I have a mac, and my ChainLadder version is 0.2.3, with R version 3.2.3. See console output below.
------------------

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.66 (7060) x86_64-apple-darwin13.4.0]

[History restored from /Users/danielmurphy/.Rapp.history]


Welcome to ChainLadder version 0.2.3

Type vignette('ChainLadder', package='ChainLadder') to access
the overall package documentation.

See demo(package='ChainLadder') for a list of demos.

More information is available on the ChainLadder project web-site:
https://github.com/mages/ChainLadder

To suppress this message use:
suppressPackageStartupMessages(library(ChainLadder))

starting httpd help server ... done
>

**Comment by Rick132** [comment]
Hey!
Thanks you very much. I just had to update my R to version 3.2.3. I have
Chain Ladder version 0.2.2 now

**Comment by chiefmurph** [comment]
It should be ChainLadder version 0.2.3. Please review my output again.

**Comment by mages** [comment]
Just to clarify version 0.2.3 is the developer version in GitHub.

**Comment by chiefmurph** [comment]
Ah. Yep. Now my ChainLadder is 0.2.2. Thanks, Markus.

**Comment by chiefmurph** [comment]
Then after
devtools::install_github("mages/ChainLadder")
back to 0.2.3.
