### ISSUE TITLE
dev.period order not correct when using plot(triang, lattice=TRUE)

### ISSUE THREAD

**Issue by AnjaliCDW** [mages/ChainLadder#71]
I have 10 development periods and when I use plot(triang, lattice=TRUE) the display of the development periods is not in order (1, 10, 2, 3, 4, 5, 6, 7, 8, 9):

![image](https://user-images.githubusercontent.com/11597441/74258181-d142d680-4ced-11ea-814d-8d0b5975b144.png)

![image](https://user-images.githubusercontent.com/11597441/74258217-ddc72f00-4ced-11ea-8c70-585264366e4d.png)

**Comment by marcopark90** [comment]
Hi, this should take care of your issue
Assuming `triangle` is your triangle
```
df <- as.data.frame(as.triangle(triangle))
df$origin <- as.numeric(df$origin)
xyplot(value ~ dev | as.factor(origin), data = df, type = "b", 
       as.table = TRUE, xlab = "dev. period", ylab = NULL)
```

**Comment by AnjaliCDW** [comment]
Great thanks!
