### ISSUE TITLE
package car is missing

### ISSUE THREAD

**Issue by leokpmak** [mages/ChainLadder#75]
Hi, 

An error message:
"Error: package or namespace load failed for ‘ChainLadder’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘car’"
is found after I have installed the package and try as.triangle function.

Can you have a look into it and please advise? Thanks a lot

Best regards

**Comment by marcopark90** [comment]
It looks like that you have to install the package `car`
https://cran.r-project.org/web/packages/car/index.html

**Comment by leokpmak** [comment]
I have assessed the link provided and installed the package by downloading the zip file. However, the same message still exist when I run library(car) or library(ChainLadder)
> library(car)
Error in library(car) : there is no package called ‘car’
> library(ChainLadder)
Error: package or namespace load failed for ‘ChainLadder’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘car’
In addition: Warning message:
package ‘ChainLadder’ was built under R version 3.5.3

**Comment by mages** [comment]
Try in the R console: 
```r
install.packages("car")
```
For more information see also the 'Installing packages' section in the [R Installation and Administration Manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installing-packages).

**Comment by leokpmak** [comment]
I have tried this before but failed:

> install.packages("car")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Warning in install.packages :
  dependency ‘pbkrtest’ is not available

  There is a binary version available but the source version is later:
    binary source needs_compilation
car  3.0-7  3.0-8             FALSE

installing the source package ‘car’

trying URL 'https://cran.rstudio.com/src/contrib/car_3.0-8.tar.gz'
Content length 499932 bytes (488 KB)
downloaded 488 KB

ERROR: dependency 'pbkrtest' is not available for package 'car'
* removing 'D:/Program Files/R/R-3.5.2/library/car'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘car’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\user\AppData\Local\Temp\Rtmp8O4z7C\downloaded_packages’
> library(car)
Error in library(car) : there is no package called ‘car’

**Comment by marcopark90** [comment]
You have two issues:
1. I assume you are on  a Windows machine. Some R packages need to be compiled, Windows can not do this natively and therefore you need to install an additional software, Rtools. https://cran.r-project.org/bin/windows/Rtools/ make sure to install the version compatible with yuor R version and add the environment path.
2. As you can see the `car` package has `pbkrtest` listed as a dependency. So you have to install this specific package before installing `car`. If you want to have all this process taken care automatically try `install.packages("package-name", dependencies = TRUE)`
