### ISSUE TITLE
actuar 

### ISSUE THREAD

**Issue by Krishnakumarshrestha** [mages/ChainLadder#78]
Every time i install this package, actuar is not found error . what might be issue?

**Comment by mages** [comment]
You probably didn't install it yet.

**Comment by Krishnakumarshrestha** [comment]
[image: image.png]

**Comment by Krishnakumarshrestha** [comment]
i think actuar is not compatible with newer version of R . I got error stating not avaliable for this verson of r.

**Comment by marcopark90** [comment]
What version of R do you have?
Probably you just have to update it to the latest release and everything will work just fine

**Comment by trinostics** [comment]
Install actuar first. I have had some issues in years past with coordinating actuar with newer versions of R.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Krishna Kumar Shrestha ***@***.***>
Sent: Friday, June 11, 2021 5:39:36 AM
To: mages/ChainLadder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mages/ChainLadder] actuar (#78)


Every time i install this package, actuar is not found error . what might be issue?
