### ISSUE TITLE
I want to change presaved claims (from ChainLadder-package) 

### ISSUE THREAD

**Issue by m007aa** [mages/ChainLadder#80]
hi :smile:
i have a short question regarding the ChainLadder package. I found a website with an instruction for the Munich Chain Ladder that is included in the ChainLadder-package.
But unfortunately, the data for "MCLpaid" and "MCLincurred" are both presaved and I have no idea how I can change them, because I want to use it for my own data.[https://cran.rstudio.com/web/packages/ChainLadder/vignettes/ChainLadder.html#munich-chain-ladder](url)
I would be very happy if somebody could help me please and I am sorry if this is a stupid question, but i am not very advanced in working with R.

Many Greetings

**Comment by mages** [comment]
Hi there,

The vignette has a short section on how to import triangles stored in an Excel spreadsheet via a CSV file: https://mages.github.io/ChainLadder/articles/ChainLadder.html#importing-triangles-from-external-data-sources

There are many other options to read in your own data. The openxlsx is pretty good if your data is stored in Excel workbooks: https://ycphs.github.io/openxlsx/reference/readWorkbook.html

I hope this helps.

**Comment by m007aa** [comment]
Hi, many thanks for the answer. I was very happy when I read that. I will try it immediately
