### ISSUE TITLE
Mack and Bootstrap Reserve Risk Calculations

### ISSUE THREAD

**Issue by LostTriangles** [mages/ChainLadder#9]
I'm quite new to R and have had some trouble pulling Mack and Bootstrap reserve risk information from R.

1. Using the pre-defined RAA incurred triangle, how do I get the "Total.Process Risk" and "Total.ParameterRisk" shown on page 35 of the package pdf https://cran.r-project.org/web/packages/ChainLadder/ChainLadder.pdf? 
I must be missing simple command somewhere but I'm only able to see total Mack S.E by year upon calling "MackChainLadder(RAA)". 

I understand Total Mack S.E ^2 = (Process Risk^2) + (Paramater Risk^2) but I'd like to see the individual breakout. 

Additionally, the Mack S.E's and Ultimates sometimes show up in abbreviated format (2.03e+06) rather than something like 2028950. Is there any way to re-format the Mack summary?

2. Similar question, but for the Bootstrap method included in the package. Rather than producing a mean simulated IBNR by accident year, is it possible to input reserves by AY and show Mean Reserve / Mean Std Dev on the summary screen?

Thanks in advance.

**Comment by fabioconcina** [comment]
Hi,
I'll answer to the first question. What you are seeing calling
MackChainLadder(RAA) is only a summary of the results of the model. You can
use

*attributes(MackChainLadder(RAA))*
to display all the attributes of the MackChainLadder object:

$names
 [1] "call"                "Triangle"
 [3] "FullTriangle"        "Models"
 [5] "f"                   "f.se"
 [7] "F.se"                "sigma"
 [9] "Mack.ProcessRisk"    "Mack.ParameterRisk"
[11] "Mack.S.E"            "weights"
[13] "alpha"               "Total.Mack.S.E"
[15] "Total.ProcessRisk"   "Total.ParameterRisk"
[17] "tail"

$class
[1] "MackChainLadder" "TriangleModel"
[3] "list"

To access the single elements you can use
*MackChainLadder(RAA)$Total.ProcessRisk* and
*MackChainLadder(RAA)$Total.ParameterRisk*.


For the exponential notation issue I would call *options(scipen = 999) *to
disable scientific notation.


2016-07-03 21:49 GMT+02:00 LostTriangles <notifications@github.com>:

**Comment by LostTriangles** [comment]
Thank you Fabio, your advice worked! Unfortunately I'm still a bit stuck on the bootstrap portion. 

*BootChainLadder(RAA)* Gives a Mean Ultimate, Mean IBNR, and IBNR SE, but no Ultimate SE.

Even without inputting Paid Information into R, if I could somehow retrieve Ultimate S.E from the BootChainLadder function by AY, I could simply do the rest of the calculations in excel. Unfortunately, I don't see one of the BootChainLadder attributes which call upon the value of Ultimate S.E.

**Comment by mages** [comment]
The ultimate SE is the same as the IBNR SE, if I am not mistaken. 

The difference between the ultimate and IBNR (or better reserve in this context) is a known quantity with no variance.

**Comment by LostTriangles** [comment]
mages, you're absolutely right. I feel quite silly given that I was going to use Ultimate SE as my Reserve SE, which again is only different by a fixed amount but didn't see the same in the incurred case.
